"""wb-wkn.44 — golden regression tests for the five named-question defects.

Every test runs against a COMMITTED synthetic dataset in the enriched shape
(`assets/nl-insights/synthetic-retail.csv`, generated by `scripts/make_synthetic.py`),
so a grader can run them with no private data — unlike the enriched tests, which are
skip-gated on a file that is not publicly downloadable.

Each test computes its ground truth with SQL written from the DATA's meaning (distinct
invoices, identified customers, all-product denominator, two-period delta) — NOT from the
engine's aggregation shape — and asserts the engine equals it through the production call
site (`execute`, and once through the whole `run_query` pipeline). Because the buggy and
fixed engines produce DIFFERENT numbers on this data, each test FAILS if its fix is
reverted — the property the addendum demands.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import duckdb
import pytest

from nl_insights.binder import VerdictKind, bind
from nl_insights.executor import Answer, NeedsClarification, execute
from nl_insights.ingestion import ingest
from nl_insights.interpreter import FrequencyConstraint, QueryIR, TopK
from nl_insights.interpreter.ir import CategoricalFilter, PeriodComparison
from nl_insights.provider import LLMRequest
from nl_insights.semantic import build_semantic_model

_SYNTHETIC = Path(__file__).resolve().parents[1] / "assets" / "nl-insights" / "synthetic-retail.csv"

_CLAIMS: dict[str, tuple[str, str | None]] = {
    "invoice_no": ("transaction_key", None),
    "invoice_type": ("dimension", None),
    "invoice_date": ("event_time", None),
    "invoice_year": ("dimension", None),
    "invoice_quarter": ("dimension", None),
    "invoice_month": ("dimension", None),
    "invoice_dow": ("dimension", None),
    "invoice_hour": ("dimension", None),
    "is_complete_quarter": ("flag", None),
    "stock_code": ("entity_key", "product"),
    "description": ("description", None),
    "line_type": ("dimension", None),
    "is_product_line": ("flag", None),
    "is_revenue_line": ("flag", None),
    "quantity": ("additive_quantity", None),
    "unit_price": ("monetary_rate", None),
    "line_revenue": ("monetary_amount", None),
    "is_return": ("flag", None),
    "customer_id": ("entity_key", "customer"),
    "is_identified_customer": ("flag", None),
    "country": ("dimension", None),
    "is_country_known": ("flag", None),
    "operator_note": ("ignore", None),
    "has_negative_price": ("flag", None),
    "is_extreme_quantity": ("flag", None),
}


class _StubProposer:
    """Feeds the recorded role claims into build_semantic_model — the discovery of the
    partition/returns/period structure still runs against the real data. An optional
    ``overrides`` dict changes individual column roles, to model a live proposer that (say)
    types the completeness column as 'ignore'."""

    name = "stub"

    def __init__(self, overrides: dict[str, tuple[str, str | None]] | None = None) -> None:
        self._claims = {**_CLAIMS, **(overrides or {})}

    def complete(self, request: LLMRequest) -> dict[str, Any]:
        return {
            "claims": [
                {"column": c, "role": r, "entity": e, "confidence": 0.9, "reasons": ["stub"]}
                for c, (r, e) in self._claims.items()
            ]
        }


@pytest.fixture
def syn(tmp_path: Path):  # type: ignore[no-untyped-def]
    result = ingest(_SYNTHETIC, data_dir=tmp_path / ".data", name="syn")
    con = duckdb.connect(str(result.duckdb_path))
    model = build_semantic_model(con, result.table, result.profile, _StubProposer())
    try:
        yield con, model, result.table
    finally:
        con.close()


def _ans(con, model, ir: QueryIR) -> Answer:  # type: ignore[no-untyped-def]
    v = bind(model, ir)
    assert v.plan is not None, v.reason
    return execute(con, v.plan, model, v.caveats)  # the production call site


def _gt(con, sql: str):  # type: ignore[no-untyped-def]
    return con.execute(sql).fetchall()


# --- CRIT-1: share_of_total over the full population, not the post-LIMIT rows ----------
def test_share_of_total_denominator_is_all_products_not_the_topk(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    a = _ans(
        con,
        model,
        QueryIR(
            measures=["net_revenue"],
            group_by=["description"],
            top_k=TopK(measure="net_revenue", k=2),
            share_of_total=True,
        ),
    )
    # INDEPENDENT denominator: revenue over ALL product lines (not the top 2).
    denom = _gt(con, f"SELECT sum(line_revenue) FROM {t} WHERE line_type='PRODUCT'")[0][0]
    for row in a.rows:
        assert row["share"] == pytest.approx(row["net_revenue"] / denom)
    # the fix's signature: the top-2 shares do NOT sum to 1.0 (the post-LIMIT bug forced
    # exactly 1.0). With >2 products, the top 2 are a strict minority of the total.
    assert sum(r["share"] for r in a.rows) < 0.99


# --- CRIT-3: the frequency denominator excludes the anonymous (null) pseudo-entity ----
def test_frequency_denominator_excludes_anonymous_entity(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    a = _ans(
        con,
        model,
        QueryIR(
            measures=["net_revenue"],
            frequency=FrequencyConstraint(
                entity="customer_id", count_of="invoice_no", op="eq", n=1
            ),
        ),
    )
    identified = _gt(con, f"SELECT sum(line_revenue) FROM {t} WHERE customer_id IS NOT NULL")[0][0]
    all_rows = _gt(con, f"SELECT sum(line_revenue) FROM {t}")[0][0]
    assert identified != all_rows  # the data actually HAS anonymous revenue to exclude
    # the denominator is the identified-customer revenue, NOT the all-rows revenue (the bug)
    assert a.rows[0]["total_measure"] == pytest.approx(identified)
    # and the coverage caveat now describes the same scope the SQL applies
    assert any("carry customer_id" in c for c in a.caveats)


# --- CRIT-5: baskets are distinct transactions, not line-pairs ------------------------
def test_basket_counts_distinct_transactions_not_line_pairs(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    a = _ans(con, model, QueryIR(basket=True, top_k=TopK(measure="pair_count", k=3)))
    # INDEPENDENT: distinct invoices containing both products, product lines, no returns.
    distinct = _gt(
        con,
        f"""WITH l AS (SELECT DISTINCT invoice_no txn, stock_code prod FROM {t}
                       WHERE line_type='PRODUCT' AND CAST(is_return AS INTEGER)=0)
            SELECT a.prod, b.prod, count(DISTINCT a.txn) FROM l a JOIN l b
            ON a.txn=b.txn AND a.prod<b.prod GROUP BY 1,2 ORDER BY 3 DESC, 1, 2 LIMIT 3""",
    )
    # the BUGGY count: line-pairs (no DISTINCT), which double-counts a repeated product line
    line_pairs = _gt(
        con,
        f"""WITH l AS (SELECT invoice_no txn, stock_code prod FROM {t}
                       WHERE line_type='PRODUCT' AND CAST(is_return AS INTEGER)=0)
            SELECT a.prod, b.prod, count(*) FROM l a JOIN l b
            ON a.txn=b.txn AND a.prod<b.prod GROUP BY 1,2 ORDER BY 3 DESC, 1, 2 LIMIT 3""",
    )
    assert distinct != line_pairs  # the data exercises the double-count
    top = a.rows[0]
    assert (top["product_a"], top["product_b"], top["pair_count"]) == distinct[0]
    assert "distinct transactions" in " ".join(a.caveats)  # scope disclosed


# --- CRIT-2: growth is computed, ranked, and excludes incomplete periods --------------
def test_growth_is_computed_ranked_and_excludes_incomplete_periods(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    a = _ans(
        con,
        model,
        QueryIR(
            measures=["net_revenue"],
            group_by=["country"],
            period_comparison=PeriodComparison(grain="quarter"),
            top_k=TopK(measure="growth", k=4),
        ),
    )
    assert {"country", "period_a_value", "period_b_value", "growth"} <= set(a.columns)
    # INDEPENDENT: two most recent COMPLETE quarters, per-country delta, ranked. The
    # incomplete quarter is excluded — including it would change the numbers.
    ind = _gt(
        con,
        f"""WITH per AS (
              SELECT country,
                (strftime(invoice_date,'%Y')||'-Q'||CAST(quarter(invoice_date) AS VARCHAR)) q,
                sum(line_revenue) rev
              FROM {t} WHERE CAST(is_complete_quarter AS INTEGER)=1 GROUP BY 1,2)
            SELECT country,
              sum(CASE WHEN q='2021-Q1' THEN rev END) a,
              sum(CASE WHEN q='2021-Q2' THEN rev END) b
            FROM per GROUP BY country
            HAVING a IS NOT NULL AND b IS NOT NULL AND a>0
            ORDER BY (b-a)/a DESC LIMIT 4""",
    )
    eng = [(r["country"], round(r["growth"], 6)) for r in a.rows]
    exp = [(c, round((b - aa) / aa, 6)) for c, aa, b in ind]
    assert eng == exp  # same ranking AND same values as the independent computation
    # the completeness clause is actually in the SQL (the structural guard depends on it)
    assert "is_complete_quarter" in a.sql
    # and it matters: the data HAS an incomplete quarter (Q3) whose exclusion is observable
    q3 = _gt(con, f"SELECT count(*) FROM {t} WHERE CAST(is_complete_quarter AS INTEGER)=0")[0][0]
    assert q3 > 0


# --- CRIT-2 (clarify): an absent period clarifies rather than returning a silent zero ---
def test_growth_absent_period_raises_clarification(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    ir = QueryIR(
        measures=["net_revenue"],
        group_by=["country"],
        period_comparison=PeriodComparison(grain="quarter", period_a="2099-Q1", period_b="2099-Q2"),
    )
    v = bind(model, ir)
    assert v.plan is not None
    with pytest.raises(NeedsClarification) as exc:
        execute(con, v.plan, model, v.caveats)  # data-dependent clarify, raised from execute
    assert "2099-Q1" in exc.value.question and exc.value.options  # names the gap + offers real ones


def test_growth_clarify_and_answer_both_flow_through_run_query_pipeline(
    syn, tmp_path: Path
) -> None:  # type: ignore[no-untyped-def]
    # Prove the growth path end-to-end through the REAL interpret -> bind -> execute
    # pipeline (run_query), not by calling the compiler helper directly: an absent period
    # becomes a CLARIFY verdict, a present one an ANSWER carrying the growth column.
    from nl_insights.jobs.pipeline import run_query
    from nl_insights.jobs.store import Dataset

    con, model, t = syn
    con.close()  # run_query opens its own connection via dataset.connect()
    result = ingest(_SYNTHETIC, data_dir=tmp_path / ".data2", name="syn2")
    con2 = duckdb.connect(str(result.duckdb_path))
    model2 = build_semantic_model(con2, result.table, result.profile, _StubProposer())
    con2.close()
    dataset = Dataset(
        dataset_id="syn2",
        table=result.table,
        duckdb_path=str(result.duckdb_path),
        row_count=model2.row_count,
        model=model2,
    )

    class _InterpretStub:
        name = "stub"

        def __init__(self, ir: QueryIR) -> None:
            self._ir = ir

        def complete(self, request: LLMRequest) -> dict[str, Any]:
            return self._ir.model_dump()

    absent = QueryIR(
        measures=["net_revenue"],
        group_by=["country"],
        period_comparison=PeriodComparison(grain="quarter", period_a="2099-Q1", period_b="2099-Q2"),
    )
    r = run_query(
        dataset=dataset,
        question="growth 2099",
        previous_ir=None,
        provider=_InterpretStub(absent),
        model="m",
        emit=lambda *a, **k: None,
    )
    assert r.kind is VerdictKind.CLARIFY and "2099-Q1" in (r.clarify_question or "")

    present = QueryIR(
        measures=["net_revenue"],
        group_by=["country"],
        period_comparison=PeriodComparison(grain="quarter"),
        top_k=TopK(measure="growth", k=4),
    )
    r2 = run_query(
        dataset=dataset,
        question="which countries grew most",
        previous_ir=None,
        provider=_InterpretStub(present),
        model="m",
        emit=lambda *a, **k: None,
    )
    assert r2.answer is not None and "growth" in r2.answer.columns


# --- MAJ-alpha: a huge growth off a tiny base is disclosed with figures, not silently ranked
def test_growth_discloses_small_base_groups_with_figures(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    a = _ans(
        con,
        model,
        QueryIR(
            measures=["net_revenue"],
            group_by=["country"],
            period_comparison=PeriodComparison(grain="quarter"),
            top_k=TopK(measure="growth", k=6),
        ),
    )
    # the synthetic data has a tiny-base country (Sark) that tops the ranking on a trivial base
    top = a.rows[0]
    assert top["country"] == "Sark" and top["growth"] > 1.0
    # ...and its small base is disclosed WITH the figure and its share of the base period,
    # rather than dropped (the user's call) — computed independently here.
    base_total = _gt(
        con,
        f"""SELECT sum(line_revenue) FROM {t}
            WHERE (strftime(invoice_date,'%Y')||'-Q'||CAST(quarter(invoice_date) AS VARCHAR))
                  = '2021-Q1'""",
    )[0][0]
    frac = top["period_a_value"] / base_total
    assert frac < 0.01  # genuinely a small base
    disclosure = next((x for x in a.assumptions if "base under" in x), None)
    assert disclosure is not None and "Sark" in disclosure and "volatile" in disclosure


# --- negative base: a % change over a negative base inverts its sign; NULL it, disclose it -
def test_growth_negative_base_is_not_ranked_and_disclosed_as_negative(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    # the synthetic has a country (Tortuga) that recovers from a net-negative Q1 to a positive
    # Q2 — a genuine turnaround that (b-a)/a would report as a large DECLINE.
    for direction in ("desc", "asc"):
        a = _ans(
            con,
            model,
            QueryIR(
                measures=["net_revenue"],
                group_by=["country"],
                period_comparison=PeriodComparison(grain="quarter"),
                top_k=TopK(measure="growth", k=10, direction=direction),
            ),
        )
        tort = next((r for r in a.rows if r["country"] == "Tortuga"), None)
        assert tort is not None and tort["period_a_value"] < 0  # negative base in the data
        assert tort["growth"] is None  # NULL, not an inverted percentage
        # never the ranked extreme in EITHER direction — a real-growth group leads
        assert a.rows[0]["country"] != "Tortuga" and a.rows[0]["growth"] is not None
    # and the negative base is disclosed AS negative (not as a small base), with the figure
    a = _ans(
        con,
        model,
        QueryIR(
            measures=["net_revenue"],
            group_by=["country"],
            period_comparison=PeriodComparison(grain="quarter"),
            top_k=TopK(measure="growth", k=10),
        ),
    )
    neg = next((x for x in a.assumptions if "NEGATIVE" in x), None)
    assert neg is not None and "Tortuga" in neg and "-294" in neg.replace(",", "")


# --- MAJ-beta: when we could not tell if the final period is complete, SAY SO -----------
def test_growth_discloses_when_period_completeness_is_unknown(tmp_path: Path) -> None:
    # A live proposer typing the completeness column as 'ignore' leaves the model with no
    # period_completeness — so the exclusion cannot happen. Silence would read as "no partial
    # periods"; instead the answer must disclose that we had no way to tell. Driven through the
    # real build_semantic_model on data that genuinely yields no completeness flag (not a
    # fabricated model).
    result = ingest(_SYNTHETIC, data_dir=tmp_path / ".data", name="synb")
    con = duckdb.connect(str(result.duckdb_path))
    model = build_semantic_model(
        con, result.table, result.profile, _StubProposer({"is_complete_quarter": ("ignore", None)})
    )
    assert model.period_completeness == []  # discovery genuinely found none
    a = _ans(
        con,
        model,
        QueryIR(
            measures=["net_revenue"],
            group_by=["country"],
            period_comparison=PeriodComparison(grain="quarter"),
            top_k=TopK(measure="growth", k=4),
        ),
    )
    assert "is_complete_quarter" not in a.sql  # nothing to exclude on
    assert any("no period-completeness flag" in c for c in a.caveats)
    con.close()


# --- CRIT-4: an out-of-vocabulary filter operator refuses, never silently defaults -----
def test_filter_operator_out_of_vocabulary_refuses(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    # model_construct bypasses the IR Literal (as a mis-generating model or a future caller
    # could); the binder must REFUSE rather than let a compile site pick the opposite branch.
    bad = CategoricalFilter.model_construct(
        column="invoice_type", op="not in", values=["cancellation"]
    )
    v = bind(model, QueryIR(measures=["net_revenue"], categorical_filters=[bad]))
    assert v.kind is VerdictKind.REFUSE and "operator" in (v.reason or "")


def test_filter_operator_literal_blocks_bad_op_at_parse() -> None:
    from pydantic import ValidationError

    with pytest.raises(ValidationError):
        CategoricalFilter(column="c", op="!=", values=["x"])  # not in {in, not_in}


# --- Partition trap, now un-skipped: top products by revenue excludes non-product money -
def test_top_products_by_revenue_excludes_non_product_lines(syn) -> None:  # type: ignore[no-untyped-def]
    con, model, t = syn
    # a naive 'group by description, order by revenue' would rank the postage line first.
    naive_top = _gt(
        con, f"SELECT description FROM {t} GROUP BY 1 ORDER BY sum(line_revenue) DESC LIMIT 1"
    )[0][0]
    assert "POSTAGE" in naive_top  # the trap exists in the data
    a = _ans(
        con,
        model,
        QueryIR(
            measures=["net_revenue"],
            group_by=["description"],
            top_k=TopK(measure="net_revenue", k=3),
        ),
    )
    assert all("POSTAGE" not in r["description"] for r in a.rows)  # partition applied
    assert "PRODUCT" in a.sql


def test_non_product_disclosure_is_correct_and_truncated(syn) -> None:  # type: ignore[no-untyped-def]
    # A bare net_revenue total legitimately includes postage/fees; the disclosure must state,
    # in numbers, exactly what non-product money is inside it. Expectation comes from OUTSIDE the
    # disclosure path - an independent group-by over the raw column - so the test cannot be
    # pinned to the code it checks; it also matches the pre-registered baseline (6 non-PRODUCT
    # types, total +59,256.00, PRODUCT +11,514.00). The disclosure sums the bound measure over
    # the line_type string, drops null/zero groups, orders by absolute value, and names only the
    # top three with a "+N more" tail - so the assertion reflects the CODE's truncated form.
    con, model, t = syn
    ind = _gt(
        con,
        f"SELECT line_type, round(sum(line_revenue), 2) FROM {t} "
        f"WHERE line_type <> 'PRODUCT' AND line_type IS NOT NULL "
        f"AND line_revenue IS NOT NULL AND line_revenue <> 0 "
        f"GROUP BY line_type ORDER BY abs(sum(line_revenue)) DESC",
    )
    exp_count = len(ind)
    exp_total = round(sum(m for _, m in ind), 2)
    exp_top3 = [lt for lt, _ in ind[:3]]
    assert exp_count == 6 and exp_total == 59256.00  # the pre-registered baseline, independently
    assert exp_top3 == ["POSTAGE", "FEE", "CARRIAGE"]  # abs-desc order is deterministic
    assert _gt(con, f"SELECT round(sum(line_revenue), 2) FROM {t} WHERE line_type = 'PRODUCT'") == [
        (11514.0,)
    ]

    a = _ans(con, model, QueryIR(measures=["net_revenue"], group_by=[]))  # the real disclosure path
    disclosure = next((s for s in a.assumptions if "non-PRODUCT" in s), None)
    assert disclosure is not None  # a disclosure is emitted at all
    assert f"{exp_count} non-PRODUCT" in disclosure  # the count of non-zero non-fact groups
    assert f"{exp_total:+,.2f}" in disclosure  # the total, covering ALL groups, not just the named
    listed = disclosure.split("(", 1)[1]  # the parenthetical contributor list
    assert 0 <= listed.index("POSTAGE") < listed.index("FEE") < listed.index("CARRIAGE")  # pinned
    assert "+3 more" in disclosure  # truncated to three named; the total still covers all six
